baseurl: "https://future.rainbowmonkeymeat.com/"
title: "Future RMM Page"
author: "Steve Miller (ssmiller25)"
canonifyurls: true
paginate: 3


params:
  tagline: "For future RMM Projects"
#   mailchimpURL: "//my-account.mailchimp.com/my-subscriber-url"

#   mastodon: "https://mastodon.url/@MyNewProduct"
#   twitter: "https://twitter.com/MyNewProduct"
#   facebook: "https://facebook.com/MyNewProduct"
#   instagram: "https://instagram.com/MyNewProduct"
#   youtube: "https://www.youtube.com/channel/MyNewChannel"
#   linkedin: "https://www.linkedin.com/company/MyNewProduct"
  github: "https://github.com/rainbowmonkeymeat"

  images:
    - "favicon.png"

theme: "lean-launch-page"

